### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by JacksonChen666** [d3xt3r0/MinecraftSkinsBot#1]
This repo has no license. [Here's more explanation about not licensing your code (on something like GitHub)](https://choosealicense.com/no-permission/). You can [find licenses here to license your code under](https://choosealicense.com/).

**Comment by d3xt3r0** [comment]
Thanks for notifying.
I have added the license information.

**Comment by JacksonChen666** [comment]
I suggest you review the "How to apply this license" section on [the license page](https://choosealicense.com/licenses/mit). [You can add the LICENSE file here](https ://github.com/d3xt3r0/MinecraftSkinsBot/community/license/new?template=MIT).

**Comment by d3xt3r0** [comment]
Done
